version: "3.3"

networks:
  server-bridge:
    driver: bridge

services:
  backend:
    image: aljabernishad/django-react-backend:latest
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - server-bridge

  frontend:
    image: aljabernishad/django-react-frontend:latest
    env_file:
      - .env
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    command: ["npm", "run", "build"]
    volumes:
      - ./frontend:/app
      - ./frontend/build:/app/build
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - server-bridge