version: "3.3"

networks:
  server-bridge:
    driver: bridge

services:
  backend:
    image: aljabernishad/django-react-backend:latest
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - server-bridge

  frontend:
    image: aljabernishad/django-react-frontend:latest
    env_file:
      - .env.local
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - server-bridge